# Generated by Django 4.1.3 on 2022-11-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_alter_contato_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='image',
            field=models.ImageField(null=True, upload_to='imagens/'),
        ),
    ]
